### PR TITLE
Fix: Selling 0 and Negative Quantity Items

### PR DESCRIPTION
**Pull request by shabananavas**
Fix for selling 0 and negative quantity items (see: https://www.drupal.org/node/2859373) and incorporated Travis' PR#23 which adds a generic pos modal and re-used that modal for the override stock question.

### CODE REVIEW

**Comment by hristos6** [comment]
Parse error: syntax error, unexpected '[' in /home/hbdetuap/public_html/commerce-kikstart/sites/all/modules/commerce_pos/includes/commerce_pos.transaction.inc on line 208
please check this

**Comment by shabananavas** [comment]
@hristos6 Can you please check now. Thanks.

**Comment by hristos6** [comment]
I will check tomorrow because of integration default cashing and must pathing all

**Comment by hristos6** [comment]
It’s seem all ok but on
http://commerce-kikstart.boyanskidesign.com/admin/commerce/pos/reports/end-of-day

Notice: Trying to get property of non-object in commerce_pos_report_end_of_day() (line 194 of /home/hbdetuap/public_html/commerce-kikstart/sites/all/modules/commerce_pos/modules/report/includes/commerce_pos_report.pages.inc).


And on http://commerce-kikstart.boyanskidesign.com/admin/commerce/pos/reports/journal-role
No transactions found

**Comment by shabananavas** [comment]
Try to checkout a fresh 2.x version and see if you're getting the errors with the fresh copy. You might need to create an issue for the errors that you're getting in commerce_pos_report_end_of_day() and journal role separately as I believe it is unrelated to this patch. There have been no changes to the reports in this patch.

**Comment by hristos6** [comment]
https://www.drupal.org/files/issues/2859339-fix_journal_role.patch
Yes this patch solve error

**Comment by shabananavas** [comment]
@hristos6 If it's working fine for you can you please update the issue: https://www.drupal.org/node/2859373. Thanks.

**Comment by hristos6** [comment]
I have updated all module with this with all last chanced and when start http://commerce-kikstart.boyanskidesign.com/admin/commerce/pos/sale
it’s  error
Parse error: syntax error, unexpected '[' in /home/hbdetuap/public_html/commerce-kikstart/sites/all/modules/commerce_pos/includes/commerce_pos.transaction.inc on line 824

**Comment by shabananavas** [comment]
@hristos6, this has been committed to 8.x-2.x dev so you shouldn't need to apply this patch. Just update your dev version and you should be good to go. Let me know if you still get an error.

**Comment by hristos6** [comment]
Now I Uninstall old me pathed version ,clear cash , delete module from root, and install again 7.x-2.x-dev<https://www.drupal.org/project/commerce_pos/releases/7.x-2.x-dev>, run update.php and from this link
http://commerce-kikstart.boyanskidesign.com/admin/commerce/pos/sale
I have this
Parse error: syntax error, unexpected '[' in /home/hbdetuap/public_html/commerce-kikstart/sites/all/modules/commerce_pos/includes/commerce_pos.transaction.inc on line 824
I created Issue
https://www.drupal.org/node/2874837

**Comment by smmccabe** [comment]
Fixed via d.o patch, closing

**Pull request closed without merging**
